ApiFunction:
  Type: AWS::Serverless::Function
  Properties:
    Runtime: python3.11
    Handler: lambda_handler.handler
    CodeUri: src/
    MemorySize: 1024
    Timeout: 30
    Policies:
      - AWSLambdaBasicExecutionRole
      - S3CrudPolicy:
          BucketName: !Ref AppBucket
    Events:
      Api:
        Type: Api
        Properties:
          Path: /{proxy+}
          Method: ANY